name: Mirror main branch to public repo
on:
  push:
    branches:
      - main
  workflow_dispatch:  # Agrega esto para ejecutarlo manualmente desde GitHub Actions

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Force mirror the repo
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add public https://misantamaria:${{ secrets.GH_TOKEN }}@github.com/misantamaria/upm_pfp_mdl_dltemp.git

          # Forzar la sobreescritura de todo el repositorio
          git fetch origin
          git reset --hard origin/main  # Esto asegura que todo se sobrescriba con la rama entrante

          # Push al repositorio público, forzando el push
          git push public main --force
    permissions:
      contents: write
